name: flutter_setup
description: A new Flutter project.

publish_to: 'none' # 

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  carousel_slider: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    -  assets/images/
    -  assets/icons/


  fonts:
    - family: Montserrat Alternates
      fonts:
        - asset: assets/fonts/MontserratAlternates-Regular.ttf
        
    - family: Noto Sans Nag Mundari
      fonts:
        - asset: assets/fonts/noto-regular.ttf
        
  
